import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useElm327 } from "@/hooks/use-elm327";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
const C = { bg: "#07111F", card: "#13243A", line: "#223B56", text: "#F5F7FA", muted: "#8CA1B8", cyan: "#29D3C5", orange: "#FFB45B" };
export default function SensorDetail() { const router = useRouter(); const { name } = useLocalSearchParams<{ name: string }>(); const { readings, connected } = useElm327(); const reading = readings.find((r) => r.name === name); const value = reading?.value || "--"; const progress = useMemo(() => Math.min(100, Math.max(0, Number(value) / (name === "RPM" ? 70 : 1.8))), [value, name]); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#07111F]"><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.text} /><Text style={s.backText}>Volver al tablero</Text></Pressable><Text style={s.eyebrow}>LECTURA EN TIEMPO REAL</Text><Text style={s.title}>{name}</Text><Text style={s.subtitle}>{connected ? "Respuesta confirmada desde la ECU" : "Sin conexión con la ECU"}</Text><View style={s.gauge}><View style={s.gaugeTop}><Text style={s.live}>● LIVE</Text><Text style={s.pid}>{reading?.command || "PID --"}</Text></View><Text style={s.value}>{value}</Text><Text style={s.unit}>{reading?.unit || ""}</Text><View style={s.bar}><View style={[s.fill, { width: `${progress}%` }]} /></View><View style={s.scale}><Text style={s.scaleText}>0</Text><Text style={s.scaleText}>Actualización automática</Text><Text style={s.scaleText}>MAX</Text></View></View><View style={s.info}><MaterialIcons name="verified" size={22} color={C.cyan} /><View style={{ flex: 1 }}><Text style={s.infoTitle}>Dato de la ECU</Text><Text style={s.infoText}>{reading ? `Última respuesta: ${new Date(reading.updatedAt).toLocaleTimeString()}` : "Toca conectar un ELM327 para comenzar."}</Text></View></View></ScrollView></ScreenContainer>; }
const s = StyleSheet.create({ content: { padding: 20, flexGrow: 1 }, back: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 45 }, backText: { color: C.muted, fontSize: 13, fontWeight: "700" }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: C.text, fontSize: 38, fontWeight: "800", marginTop: 7 }, subtitle: { color: C.muted, fontSize: 13, marginTop: 6 }, gauge: { backgroundColor: C.card, borderColor: C.line, borderWidth: 1, borderRadius: 26, padding: 22, marginTop: 28, minHeight: 300, justifyContent: "center" }, gaugeTop: { flexDirection: "row", justifyContent: "space-between" }, live: { color: C.cyan, fontWeight: "800", fontSize: 11 }, pid: { color: C.muted, fontSize: 11, fontWeight: "700" }, value: { color: C.text, fontSize: 86, fontWeight: "800", textAlign: "center", marginTop: 35, letterSpacing: -4 }, unit: { color: C.muted, fontSize: 16, textAlign: "center", marginTop: -5 }, bar: { height: 8, backgroundColor: C.line, borderRadius: 8, marginTop: 35, overflow: "hidden" }, fill: { height: 8, backgroundColor: C.cyan, borderRadius: 8 }, scale: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 }, scaleText: { color: C.muted, fontSize: 10 }, info: { flexDirection: "row", gap: 12, alignItems: "center", backgroundColor: "#102E3B", borderRadius: 17, padding: 15, marginTop: 18 }, infoTitle: { color: C.text, fontWeight: "800", fontSize: 13 }, infoText: { color: C.muted, fontSize: 11, marginTop: 4 } });
