import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useElm327 } from "@/hooks/use-elm327";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
const C = { bg: "#050B13", surface: "#0B1725", line: "#1F3A55", text: "#F5F7FA", muted: "#86A0B7", green: "#21F59A", amber: "#FFB84D", red: "#FF4D65" };
const presets = [{ code: "ATZ", label: "Reset" }, { code: "ATI", label: "Identidad" }, { code: "ATSP0", label: "Auto protocolo" }, { code: "0100", label: "PIDs" }, { code: "010C", label: "RPM" }, { code: "010D", label: "Velocidad" }, { code: "03", label: "DTC" }, { code: "04", label: "BORRAR DTC", risk: true }, { code: "ATWS", label: "Wake", risk: true }, { code: "ATSH", label: "Cabecera", risk: true }];
export default function TerminalScreen() { const router = useRouter(); const obd = useElm327(); const [command, setCommand] = useState("ATI"); const [log, setLog] = useState<string[]>([]); const send = async () => { const value = command.trim().toUpperCase(); if (!value) return; setLog((old) => [...old, `elm327@ecu:~$ ${value}`]); try { const response = await obd.sendCommand(value); setLog((old) => [...old, response]); } catch (e: any) { setLog((old) => [...old, `ERROR: ${e?.message || "sin conexión"}`]); } }; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#050B13]"><View style={s.content}><Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.text} /><Text style={s.backText}>Volver</Text></Pressable><Text style={s.eyebrow}>COMUNICACIÓN ECU</Text><Text style={s.title}>Terminal AT</Text><Text style={s.subtitle}>Consola tipo Linux: comandos enviados y respuestas reales del ELM327.</Text><View style={s.connection}><View style={[s.dot, { backgroundColor: obd.connected ? C.green : C.amber }]} /><Text style={s.connectionText}>{obd.status}</Text></View><View style={s.log}><ScrollView contentContainerStyle={{ padding: 15 }}><Text style={s.mono}>{log.length ? log.join("\n\n") : "elm327@ecu:~$ Conecta el adaptador para comenzar"}</Text></ScrollView></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.presets}>{presets.map((item) => <Pressable key={item.code} onPress={() => setCommand(item.code)} style={[s.preset, item.risk && s.riskPreset]}><Text style={[s.presetText, item.risk && s.riskText]}>{item.code}</Text><Text style={[s.presetLabel, item.risk && s.riskText]}>{item.label}</Text></Pressable>)}</ScrollView><View style={s.inputRow}><TextInput value={command} onChangeText={setCommand} autoCapitalize="characters" placeholder="Ej. 010C" placeholderTextColor={C.muted} style={s.input} onSubmitEditing={send} returnKeyType="send" /><Pressable onPress={send} style={s.send}><MaterialIcons name="send" size={20} color={C.bg} /></Pressable></View><Text style={s.warning}>Ámbar: configuración. Rojo: alto riesgo; puede borrar DTC o cambiar la comunicación. Solo ejecuta comandos que conozcas.</Text></View></ScreenContainer>; }
const s = StyleSheet.create({ content: { flex: 1, padding: 20 }, back: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 30 }, backText: { color: C.muted, fontWeight: "700" }, eyebrow: { color: C.green, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: C.text, fontSize: 32, fontWeight: "800", marginTop: 6 }, subtitle: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 6 }, connection: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 15 }, dot: { width: 8, height: 8, borderRadius: 8 }, connectionText: { color: C.muted, fontSize: 12 }, log: { flex: 1, backgroundColor: "#020609", borderColor: C.green + "88", borderWidth: 1, borderRadius: 17, marginTop: 15, minHeight: 230 }, mono: { color: C.green, fontSize: 12, lineHeight: 20, fontFamily: "monospace" }, presets: { gap: 8, paddingVertical: 12 }, preset: { backgroundColor: C.surface, borderColor: C.amber, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 }, riskPreset: { borderColor: C.red, backgroundColor: "#35131C" }, presetText: { color: C.amber, fontSize: 11, fontWeight: "900" }, presetLabel: { color: C.muted, fontSize: 9, marginTop: 3 }, riskText: { color: C.red }, inputRow: { flexDirection: "row", gap: 9 }, input: { flex: 1, backgroundColor: C.surface, color: C.green, borderColor: C.green + "88", borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, height: 50, fontFamily: "monospace" }, send: { width: 50, height: 50, borderRadius: 13, backgroundColor: C.green, justifyContent: "center", alignItems: "center" }, warning: { color: C.muted, fontSize: 10, lineHeight: 15, marginTop: 12 } });
