import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useElm327 } from "@/hooks/use-elm327";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
const C = { bg: "#07111F", surface: "#0E1B2C", line: "#223B56", text: "#F5F7FA", muted: "#8CA1B8", cyan: "#29D3C5", orange: "#FFB45B", red: "#FF6B6B" };
const presets = ["ATZ", "ATI", "ATSP0", "0100", "010C", "010D", "03", "04"];
export default function TerminalScreen() { const router = useRouter(); const obd = useElm327(); const [command, setCommand] = useState("ATI"); const [log, setLog] = useState<string[]>([]); const send = async () => { const value = command.trim().toUpperCase(); if (!value) return; setLog((old) => [...old, `> ${value}`]); try { const response = await obd.sendCommand(value); setLog((old) => [...old, response]); } catch (e: any) { setLog((old) => [...old, `ERROR: ${e?.message || "sin conexión"}`]); } }; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#07111F]"><View style={s.content}><Pressable onPress={() => router.back()} style={s.back}><MaterialIcons name="arrow-back" size={22} color={C.text} /><Text style={s.backText}>Volver</Text></Pressable><Text style={s.eyebrow}>COMUNICACIÓN ECU</Text><Text style={s.title}>Terminal AT</Text><Text style={s.subtitle}>Envía comandos ELM327 y recibe la respuesta cruda del adaptador.</Text><View style={s.connection}><View style={[s.dot, { backgroundColor: obd.connected ? C.cyan : C.orange }]} /><Text style={s.connectionText}>{obd.status}</Text></View><View style={s.log}><ScrollView contentContainerStyle={{ padding: 15 }}><Text style={s.mono}>{log.length ? log.join("\n\n") : "Terminal lista. Conecta el adaptador para comenzar."}</Text></ScrollView></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.presets}>{presets.map((item) => <Pressable key={item} onPress={() => setCommand(item)} style={s.preset}><Text style={s.presetText}>{item}</Text></Pressable>)}</ScrollView><View style={s.inputRow}><TextInput value={command} onChangeText={setCommand} autoCapitalize="characters" placeholder="Ej. 010C" placeholderTextColor={C.muted} style={s.input} onSubmitEditing={send} returnKeyType="send" /><Pressable onPress={send} style={s.send}><MaterialIcons name="send" size={20} color={C.bg} /></Pressable></View><Text style={s.warning}>Usa comandos de lectura y configuración ELM327. No envíes comandos de escritura propietarios sin conocer su efecto.</Text></View></ScreenContainer>; }
const s = StyleSheet.create({ content: { flex: 1, padding: 20 }, back: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 30 }, backText: { color: C.muted, fontWeight: "700" }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: C.text, fontSize: 32, fontWeight: "800", marginTop: 6 }, subtitle: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 6 }, connection: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 15 }, dot: { width: 8, height: 8, borderRadius: 8 }, connectionText: { color: C.muted, fontSize: 12 }, log: { flex: 1, backgroundColor: "#050B13", borderColor: C.line, borderWidth: 1, borderRadius: 17, marginTop: 15, minHeight: 230 }, mono: { color: C.cyan, fontSize: 12, lineHeight: 20, fontFamily: "monospace" }, presets: { gap: 8, paddingVertical: 12 }, preset: { backgroundColor: C.surface, borderColor: C.line, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 }, presetText: { color: C.orange, fontSize: 11, fontWeight: "800" }, inputRow: { flexDirection: "row", gap: 9 }, input: { flex: 1, backgroundColor: C.surface, color: C.text, borderColor: C.line, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, height: 50, fontFamily: "monospace" }, send: { width: 50, height: 50, borderRadius: 13, backgroundColor: C.cyan, justifyContent: "center", alignItems: "center" }, warning: { color: C.muted, fontSize: 10, lineHeight: 15, marginTop: 12 } });
